### ISSUE TITLE
confused about `model_step`, fixed-length or not?

### ISSUE THREAD

**Issue by moonlight1776** [mogician233/KSR#1]
Hi MogicianXD,
I am confused about these code.
`self.pos_len = train_items.shape[1]`
and
 ```
for t in range(0, X.shape[1]):
            y, h, MN = self.model_step(Sx[:, t, :], X[:, t], h, MN)
```
Are you set fixed-length for every session by padding and truncate, because I don't find any preprocessed code?

Waiting for your answer and thank you for sharing!

**Comment by MogicianXD** [comment]
Yes. I have padded them with zeros. You can see corresponding codes in the function `process` of `run_KSR.py`.


```python
            for i in range(max_len - 1 - k):
                prepare.append([sid, 0])
```


It's my honor to share. Thank u!
